sudo: required
services:
  - docker
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/640d416751eeb9fca7c3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
  - docker build --tag="my-ws-mock" .
  - docker ps -a
  - docker run -t -i -p 2525:2525 -p 8010:8010 --name='my-ws-mock' my-ws-mock

before_script:
  - npm prune
  - npm run test:serve
script:
  - npm run lint
  - npm run test:single
  - npm run test:check-coverage
  - npm run test:upload-coverage
  - npm run bundle
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
